import { StyleSheet } from 'react-native';
import { lightColors, radius, spacing, touch } from '../../lib/theme';

export const makeStyles = (colors: typeof lightColors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.surface },
  header: { position: 'relative', alignItems: 'center', justifyContent: 'center', minHeight: 56, paddingHorizontal: spacing.xl, paddingVertical: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.borderLight },
  title: { fontSize: 18, fontWeight: 'bold', color: colors.text },
  headerAction: { position: 'absolute', top: 0, bottom: 0, width: touch.min, alignItems: 'center', justifyContent: 'center' },
  headerBack: { left: spacing.md },
  headerClose: { right: spacing.md },
  scroll: { flex: 1 },
  content: { flexGrow: 1, padding: spacing.xl, paddingBottom: spacing.xl, gap: spacing.lg },
  colorSpecimen: { overflow: 'hidden', borderRadius: radius.md, borderCurve: 'continuous', borderWidth: 1, borderColor: colors.borderLight },
  swatch: { height: 156, overflow: 'hidden', justifyContent: 'flex-end', paddingVertical: spacing.xxl, paddingHorizontal: spacing.xl },
  finishOverlay: { ...StyleSheet.absoluteFillObject, overflow: 'hidden' },
  swatchLabel: { gap: spacing.xs, zIndex: 1, position: 'relative' },
  swatchBrandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  swatchBrand: { fontSize: 14, fontWeight: '600', opacity: 0.82 },
  swatchName: { fontSize: 26, lineHeight: 32, fontWeight: '700', letterSpacing: -0.3 },
  nameTooltip: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.sm, zIndex: 2 },
  nameTooltipText: { fontSize: 16, lineHeight: 22, fontWeight: '600' },
  swatchCode: { fontSize: 18, fontWeight: '600', marginTop: spacing.xs },
  swatchHex: { fontSize: 13, fontWeight: '600', opacity: 0.84, letterSpacing: 0.6 },
  sectionTitle: { fontSize: 12, color: colors.textMuted, fontWeight: '600' },
  editBtn: { padding: spacing.sm, marginRight: -spacing.sm },
  toneRail: { height: 34, flexDirection: 'row', borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.18)' },
  toneStep: { flex: 1 },
  detailCard: { flexDirection: 'row', flexWrap: 'wrap', backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.borderLight, borderRadius: radius.md, paddingTop: spacing.lg },
  compactItem: { width: '50%', paddingHorizontal: spacing.lg, paddingBottom: spacing.lg },
  compactLabel: { fontSize: 11, color: colors.textMuted },
  compactValue: { fontSize: 15, color: colors.text, fontWeight: '600', marginTop: 2 },
  ledgerCard: { backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.borderLight, borderRadius: radius.md, padding: spacing.lg, gap: spacing.md },
  stockStatusRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.lg },
  stockItem: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  statusDot: { width: 10, height: 10, borderRadius: 5 },
  stockStatusText: { fontSize: 14, color: colors.textSecondary, fontVariant: ['tabular-nums'] },
  field: { marginBottom: spacing.lg },
  label: { fontSize: 12, color: colors.textMuted, marginBottom: spacing.xs },
  input: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, padding: spacing.lg, color: colors.text },
  readonly: { borderWidth: 1, borderColor: colors.borderLight, borderRadius: radius.sm, padding: spacing.lg, color: colors.textFaint, backgroundColor: colors.surfaceAlt },
  quote: { fontSize: 14, lineHeight: 20, color: colors.textSecondary },
  hexRow: { flexDirection: 'row', alignItems: 'center' },
  hexInput: { flex: 1 },
  notesInput: { minHeight: 80, alignItems: 'flex-start' },
  previewSwatch: { marginLeft: spacing.md, width: touch.min, height: touch.min, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border },
  cameraBtn: { marginLeft: spacing.md, width: touch.min, height: touch.min, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: spacing.xs },
  chip: { paddingHorizontal: spacing.lg, paddingVertical: spacing.md, borderRadius: radius.pill, backgroundColor: colors.chip, marginRight: spacing.md, marginBottom: spacing.md },
  chipOn: { backgroundColor: colors.primary },
  chipText: { fontSize: 13, color: colors.textSecondary },
  chipTextOn: { color: colors.onPrimary, fontWeight: 'bold' },
  sectionGap: { marginTop: spacing.lg },
  masterText: { color: colors.textFaint, fontSize: 12, marginTop: -spacing.md, marginBottom: spacing.lg },
  addGroup: { borderWidth: 1, borderColor: colors.borderLight, borderRadius: radius.md, padding: spacing.lg, gap: spacing.sm },
  boxPicker: { minHeight: touch.min, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, paddingHorizontal: spacing.lg },
  boxPickerText: { flex: 1, color: colors.text, fontSize: 14 },
  fullWidth: { alignSelf: 'stretch' },
  toggleRow: { flexDirection: 'row', gap: spacing.md },
  toggleButton: { flex: 1, flexDirection: 'row' },
  toggleIcon: { marginRight: spacing.xs },
  button: { minHeight: touch.min, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.xl, paddingVertical: spacing.lg, alignItems: 'center', justifyContent: 'center' },
  primaryButton: { backgroundColor: colors.primary, borderColor: colors.primary },
  deleteButton: { borderColor: colors.danger, backgroundColor: colors.dangerSoft },
  buttonText: { color: colors.text, fontWeight: 'bold' },
  primaryButtonText: { color: colors.onPrimary, fontWeight: 'bold' },
  deleteButtonText: { color: colors.dangerText, fontWeight: 'bold' },
  textAction: { alignSelf: 'center', paddingVertical: spacing.lg, paddingHorizontal: spacing.xl },
  textActionLabel: { fontSize: 14, color: colors.dangerText, fontWeight: 'bold' },
  saveArea: { backgroundColor: colors.surface, paddingHorizontal: spacing.xl, paddingTop: spacing.md },
  saveBtn: { minHeight: touch.min, borderRadius: radius.md, backgroundColor: colors.primary, paddingHorizontal: spacing.xl, paddingVertical: spacing.lg, alignItems: 'center', justifyContent: 'center' },
  saveBtnDisabled: { backgroundColor: colors.primaryDisabled },
  saveBtnText: { color: colors.onPrimary, fontSize: 16, fontWeight: 'bold' },
  empty: { textAlign: 'center', marginTop: 40, color: colors.textPlaceholder },
});

export type PaintDetailStyles = ReturnType<typeof makeStyles>;
