import { StyleSheet } from 'react-native';
import { lightColors, radius, spacing, touch } from '../../lib/theme';

export const makeStyles = (colors: typeof lightColors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.surface },
  header: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingLeft: spacing.xl, paddingRight: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.borderLight },
  backBtn: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 2 },
  headerButton: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 18, fontWeight: 'bold', color: colors.text },
  scroll: { flex: 1 },
  content: { padding: spacing.xl, gap: spacing.lg },
  titleBlock: { gap: spacing.xs },
  nameRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  nameActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  name: { fontSize: 20, fontWeight: '700', color: colors.text },
  nameEditInput: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, padding: 10, color: colors.text, fontSize: 20, fontWeight: '700' },
  maker: { fontSize: 14, color: colors.textMuted },
  card: { backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.borderLight, borderRadius: radius.md, padding: spacing.lg, gap: spacing.md },
  field: { gap: spacing.xs },
  fieldRow: { flexDirection: 'row', gap: spacing.lg },
  fieldHalf: { flex: 1 },
  sectionTitle: { fontSize: 12, color: colors.textMuted, fontWeight: '600' },
  pickerText: { color: colors.text, fontSize: 14, fontWeight: '600' },
  input: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, padding: 10, color: colors.text },
  noteInput: { minHeight: 72, alignItems: 'flex-start' },
  tabBar: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: colors.borderLight },
  tabBtn: { flex: 1, padding: spacing.md, alignItems: 'center' },
  tabBtnActive: { borderBottomWidth: 2, borderBottomColor: colors.primary },
  tabText: { fontSize: 13, color: colors.textPlaceholder },
  tabTextActive: { color: colors.primaryText, fontWeight: 'bold' },
  empty: { textAlign: 'center', marginTop: 40, color: colors.textPlaceholder },
  actionBar: { flexDirection: 'row', gap: spacing.md, padding: spacing.xl, borderTopWidth: 1, borderTopColor: colors.borderLight },
  actionButton: { flex: 1, minHeight: touch.min, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, borderWidth: 1, borderRadius: radius.md },
  moveButton: { borderColor: colors.primary },
  deleteButton: { borderColor: colors.danger },
  actionText: { color: colors.primaryText, fontWeight: '700' },
  deleteText: { color: colors.dangerText },
  editBar: { padding: spacing.xl, borderTopWidth: 1, borderTopColor: colors.borderLight },
  saveEditBtn: { minHeight: touch.min, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary, borderRadius: radius.md },
  saveEditBtnDisabled: { backgroundColor: colors.primaryDisabled },
  saveEditBtnText: { color: colors.onPrimary, fontWeight: '700', fontSize: 16 },
});

export type KitWishlistDetailStyles = ReturnType<typeof makeStyles>;
